### ISSUE TITLE
Full clone of history necessary?

### ISSUE THREAD

**Issue by cookiengineer** [falconindy/asp#12]
Hey there,

I'm currently trying to figure out if it's possible to save bandwidth by modifying this specific line: https://github.com/falconindy/asp/blob/5d64421cd9538cce28b9f554e2116495df9be49f/package.inc.sh#L170

Currently, the line does a `git clone --single-branch --branch ...` behind the scenes and I'm wondering if a `--depth=1` would also be enough as I would probably not want to revert the history and this would save me a shitload of bandwidth on my third-country-like connected machines.

So I guess my questions are:

- Is a full git history necessary and used somewhere else by asp?

**Comment by falconindy** [comment]
If you don't need history, then you probably don't want to use `asp checkout`, but rather `asp export`.

**Comment by cookiengineer** [comment]
Yes, that's probably what I want.

For others when they find this issue: `asp export` uses `git archive` behind the scenes, so it's without a git history and just a tar archive.
