### ISSUE TITLE
When used list-all anything that not in community is prefixed as package

### ISSUE THREAD

**Issue by jristz** [falconindy/asp#14]
Due on how is build if someone run list-all any package not belong to [community] is prefixed as package

```
packages/zlib
packages/zsh
packages/zvbi
packages/zziplib
community/0ad
community/0ad-data
community/4ti2
community/6tunnel
community/9base
```

this dificult indentify from which repo belong a package and could cause confusion.

Should be possible to make it distingish and properly show [code] [extra] [comunity] [multilib] like abs used to do?

**Comment by falconindy** [comment]
The package/ and community/ prefixes correspond to the svn2git repositories. No one should care what binary package repo a *source* package belongs to. To that end, the right thing to do here is to remove the packages/ and community/ prefixes.

**Comment by falconindy** [comment]
283d692d994d8d3258822c59c679130e68d2499e removes the prefixes.
