### ISSUE TITLE
Add option to choose http or git protocol

### ISSUE THREAD

**Issue by mrbanie** [falconindy/asp#15]
Hello,
please add the option to choose between http or git protocol. This is useful for people behind a http proxy which blocks git protocol.

Regards

**Comment by falconindy** [comment]
I was holding off on doing this because older versions of git didn't have feature parity between git and http protocols. That seems to have been resolved.

In the meantime, you can fix this by cd'ing into your $ASPROOT and running:

```sh
git remote set-url packages "https://git.archlinux.org/svntogit/packages.git"
git remote set-url community "https://git.archlinux.org/svntogit/community.git"
```
