### ISSUE TITLE
asp lists unavailable packages

### ISSUE THREAD

**Issue by NicoHood** [falconindy/asp#19]
```
[arch@arch test]$ asp list-arches appdata-tools
remote: Counting objects: 38, done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 38 (delta 6), reused 31 (delta 3)
Unpacking objects: 100% (38/38), done.
From git://git.archlinux.org/svntogit/packages
 * branch            packages/appdata-tools -> FETCH_HEAD
 * [new branch]      packages/appdata-tools -> packages/packages/appdata-tools

[arch@arch test]$ asp list-arches appdata-tools

```

**Comment by falconindy** [comment]
Ultimately, this seems like some to fix in SVN, no?

**Comment by NicoHood** [comment]
We have lots of outdated PKGBUILDs in svn, yes. They should be deleted if possible. pacman -Sl shows all packages, maybe this can be used as master reference which packages exist and which not?

**Comment by falconindy** [comment]
asp isn't interested in what pacman thinks. It mirrors the SVN repo. Why does this matter to you?

**Comment by NicoHood** [comment]
I want to parse all PKGBUILDs of all packages in the official repos.

I cannot just git clone the two svn2git repos, as they contains (as shown above) outdated data sometimes and duplicates (some PKGBUILDs exist in packages and community when they move from community to extra). Also svn2git always shows the latest commit, used for testing, but not the the normal repos.

So I found your tool. What I try to do now is write a script which:
* Go through all packages (`pacman -Sl` preferred over `asp list-all`)
* Get the architecture of the package (as `any` is treated different for asp)
* Get the PKGBUILD via `asp export`

Afterwards I want to parse all packages with my [LSD](https://nicohood.github.io/LSD/).

**Comment by falconindy** [comment]
Well, svn2git is what asp is based on, so it seems odd to suggest that it doesn't have the repo-released packages.

What you're doing seems fine, with pacman -Sl as a starting to.
