### ISSUE TITLE
Split packages -- Feature or bug?

### ISSUE THREAD

**Issue by thiagowfx** [falconindy/asp#8]
Today I just tried to do a 

```
asp export gvim-python3
```

However, this outputs:

```
error: unknown package: gvim-python3
```

But

```
asp export vim
```

works okay. Now, the PKGBUILD of vim contains:

```
pkgbase=vim
pkgname=('vim-minimal' 'vim' 'vim-python3' 'gvim' 'gvim-python3' 'vim-runtime')
```

So you see the issue: asp only recognizes **pkgbase**. Now, it would be nice to be able to export other packages from package name. 

Did you keep asp this way to be simple (feature) or it should have been able to export gvim-python3 (bug)?

**Comment by progandy** [comment]
It should be possible with archweb:
* get ```https://www.archlinux.org/packages/search/json/?q=PACKAGE_NAME```
* extract ```arch```, ```repo``` and ```pkgname``` from results
* get ```https://www.archlinux.org/packages/$repo/$arch/$pkgname/json/```
* extract ```pkgbase```
